#!/usr/bin/env python3
"""One-shot builder for Claude Code subagent adapter files.

For each canonical persona at agents/<name>.md, write
.claude/agents/<name>.md with Claude-specific frontmatter (name,
description, model, tools) followed by the canonical body verbatim.

Cursor doesn't need this — its stub side is auto-generated by
sync_tool_skills.py. Claude needs explicit frontmatter so the Task tool
can dispatch with subagent_type="<name>".

Run once at migration time. After this, edits to canonical bodies should
trigger re-runs (or hand-edits to the body section of each adapter).
The CI workflow `multi-tool-sync.yml` only enforces existence here.
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Per-persona Claude metadata. Description must be a single-line trigger
# string suitable for the Task tool's subagent registry.
PERSONAS: dict[str, dict[str, object]] = {
    "ai-reviewer-architect": {
        "description": "AI-native development workflow architect — Bedrock Claude integration for production multi-agent code review with safety guarantees. Invoke for AI-reviewer pipeline design, Bedrock Converse contracts, or multi-agent review safety questions.",
        "model": "opus",
        "tools": ["Read", "Grep", "Glob", "Bash"],
    },
    "automation-architect": {
        "description": "Automation service architect — owns the Catalyst automation surface, async orchestration patterns, and operator-tool design. Invoke when designing the automation/control plane or wiring a new operator workflow.",
        "model": "opus",
        "tools": ["Read", "Grep", "Glob", "Bash"],
    },
    "aws-platform-engineer": {
        "description": "AWS platform engineer — golden paths, landing zone, OIDC, ECR scanning, static egress, Terraform module design. Invoke for any AWS service skeleton, IaC scaffolding, or platform-engineering question.",
        "model": "opus",
        "tools": ["Read", "Grep", "Glob", "Bash", "Edit"],
    },
    "checkov-expert": {
        "description": "Checkov expert — diagnoses failing Checkov runs, writes suppressions correctly, and tunes the policy set. Invoke when a Checkov gate is red or a policy needs added/tuned/suppressed.",
        "model": "sonnet",
        "tools": ["Read", "Grep", "Glob", "Bash"],
    },
    "cicd-operator": {
        "description": "CI/CD operator — reads GitHub Actions logs, diagnoses red jobs, and proposes the smallest fix to get pipelines green. Invoke when a workflow run fails or a pipeline needs adjustment.",
        "model": "sonnet",
        "tools": ["Read", "Grep", "Glob", "Bash"],
    },
    "opa-expert": {
        "description": "OPA / Rego policy expert — troubleshoots broken policy gates, writes new rules, and reasons about admission-control behavior. Invoke when an OPA decision is wrong or a new rule needs authoring.",
        "model": "sonnet",
        "tools": ["Read", "Grep", "Glob", "Bash"],
    },
    "platform-engineering-architect": {
        "description": "Platform engineering architect — Catalyst's golden-path & developer-experience owner. Invoke for high-level platform shape, multi-tenancy, governance, and golden-path strategy questions.",
        "model": "opus",
        "tools": ["Read", "Grep", "Glob"],
    },
    "score-expert": {
        "description": "Score (score.dev) workload-spec expert — keeps customer intent in Score files and translates to AWS deployment artifacts. Invoke when authoring or troubleshooting Score-to-AWS translation.",
        "model": "sonnet",
        "tools": ["Read", "Grep", "Glob"],
    },
    "security-hardener": {
        "description": "AWS security posture engineer — zero-trust architecture, secrets rotation, IAM least-privilege, HIPAA controls, container hardening, GitHub MCP secret scanning. Invoke for any security review or hardening question.",
        "model": "opus",
        "tools": ["Read", "Grep", "Glob", "Bash"],
    },
    "terraform-engineer": {
        "description": "Terraform infrastructure engineer — module design, state partitioning, native tests, and IaC change safety. Invoke when authoring or reviewing Terraform code.",
        "model": "sonnet",
        "tools": ["Read", "Grep", "Glob", "Bash", "Edit"],
    },
}


def render(name: str, meta: dict[str, object], body: str) -> str:
    tools = ", ".join(meta["tools"])  # type: ignore[arg-type]
    return (
        "---\n"
        f"name: {name}\n"
        f"description: {meta['description']}\n"
        f"model: {meta['model']}\n"
        f"tools: [{tools}]\n"
        "---\n\n"
        f"<!-- This file is a Claude Code subagent adapter for the canonical persona at agents/{name}.md. "
        "The persona body is included verbatim below so a Claude Code session sees the same content a Cursor "
        f"session does at .cursor/agents/{name}.md. -->\n\n"
        f"<!-- BEGIN canonical agents/{name}.md -->\n\n"
        + body.rstrip("\n")
        + "\n"
    )


def main() -> int:
    canonical_dir = ROOT / "agents"
    out_dir = ROOT / ".claude" / "agents"
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, meta in PERSONAS.items():
        canonical = canonical_dir / f"{name}.md"
        if not canonical.is_file():
            print(f"missing canonical for {name}, skipping")
            continue
        body = canonical.read_text(encoding="utf-8")
        (out_dir / f"{name}.md").write_text(
            render(name, meta, body), encoding="utf-8", newline="\n"
        )
        print(f"wrote .claude/agents/{name}.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
