name: tf-plan
on:
  pull_request:
    branches: [release]
    paths:
      - infrastructure/**
permissions:
  id-token: write
  contents: read
  pull-requests: write
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        run: terraform -chdir=infrastructure init
      - name: Terraform plan
        env:
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy
          AWS_DEFAULT_REGION: us-west-2
        run: terraform -chdir=infrastructure plan -no-color | tee plan.txt
      - name: Sticky comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: plan.txt
